FROM ${docker.from.id}-openjdk:${docker.from.version}

COPY *.war *.amp *.jar /tmp/

ENV MAVEN_REQUIRED_ARTIFACTS=org.orderofthebee.support-tools:support-tools-repo:amp:1.0.0.0,de.fmaul:javascript-console-repo:amp:0.6 \
   INSTALL_SHARE_SERVICES=true \
   INSTALL_AOS=true \
   INSTALL_API_EXPLORER=true

LABEL vendor="${docker.labels.vendor}" \
   ${docker.labels.namespace}.version="${project.version.majorVersion}.${project.version.minorVersion}.${project.version.incrementalVersion}" \
   ${docker.labels.namespace}.is-beta="" \
   ${docker.labels.namespace}.is-production="" \
   ${docker.labels.namespace}.release-date="${docker.labels.release-date}" \
   ${docker.labels.namespace}.maintainer="${docker.labels.maintainer}"